
spring.mongodb.database=ecovault
spring.application.name=mongoapp 
spring.mongodb.uri=mongodb+srv://brunojgiacomini:<nsnFalEWXTYhrXAz>@cluster0.9m4pekm.mongodb.net/?appName=Cluster0
server.port=8080 