
spring.mongodb.uri=mongodb+srv://brunojgiacomini:nsnFalEWXTYhrXAz@cluster0.9m4pekm.mongodb.net/ecovault?appName=Cluster0
spring.mongodb.database=ecovault
spring.data.mongodb.auto-index-creation=true
spring.application.name=ecovault-backend
server.port=8080
jwt.secret=BOS4v2XIA344OrE6TvmRZMeaW+Inr8rbtsRvh9YRhe4=